execute at @e[type=zombie,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_zombie_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_zombie_4
execute at @e[type=zombie,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_zombie_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_zombie_4
execute at @e[type=zombie,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_zombie_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_zombie_4
execute at @e[type=zombie,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_zombie_4
execute at @e[type=skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_skeleton_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_skeleton_4
execute at @e[type=skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_skeleton_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_skeleton_4
execute at @e[type=skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_skeleton_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_skeleton_4
execute at @e[type=skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_skeleton_4
execute at @e[type=creeper,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_creeper_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_creeper_4
execute at @e[type=creeper,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_creeper_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_creeper_4
execute at @e[type=creeper,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_creeper_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_creeper_4
execute at @e[type=creeper,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_creeper_4
execute at @e[type=spider,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_spider_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_spider_4
execute at @e[type=spider,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_spider_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_spider_4
execute at @e[type=spider,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_spider_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_spider_4
execute at @e[type=spider,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_spider_4
execute at @e[type=enderman,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_enderman_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_enderman_4
execute at @e[type=enderman,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_enderman_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_enderman_4
execute at @e[type=enderman,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_enderman_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_enderman_4
execute at @e[type=enderman,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_enderman_4
execute at @e[type=wither_skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_wither_skeleton_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_wither_skeleton_4
execute at @e[type=wither_skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_wither_skeleton_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_wither_skeleton_4
execute at @e[type=wither_skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_wither_skeleton_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_wither_skeleton_4
execute at @e[type=wither_skeleton,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_wither_skeleton_4
execute at @e[type=blaze,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_blaze_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_blaze_4
execute at @e[type=blaze,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_blaze_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_blaze_4
execute at @e[type=blaze,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_blaze_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_blaze_4
execute at @e[type=blaze,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_blaze_4
execute at @e[type=ghast,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_ghast_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_ghast_4
execute at @e[type=ghast,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_ghast_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_ghast_4
execute at @e[type=ghast,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_ghast_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_ghast_4
execute at @e[type=ghast,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_ghast_4
execute at @e[type=cow,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_cow_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_cow_4
execute at @e[type=cow,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_cow_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_cow_4
execute at @e[type=cow,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_cow_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_cow_4
execute at @e[type=cow,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_cow_4
execute at @e[type=sheep,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_sheep_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_sheep_4
execute at @e[type=sheep,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_sheep_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_sheep_4
execute at @e[type=sheep,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_sheep_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_sheep_4
execute at @e[type=sheep,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_sheep_4
execute at @e[type=pig,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_pig_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_pig_4
execute at @e[type=pig,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_pig_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_pig_4
execute at @e[type=pig,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_pig_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_pig_4
execute at @e[type=pig,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_pig_4
execute at @e[type=chicken,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_chicken_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_chicken_4
execute at @e[type=chicken,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_chicken_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_chicken_4
execute at @e[type=chicken,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_chicken_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_chicken_4
execute at @e[type=chicken,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_chicken_4
execute at @e[type=rabbit,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_rabbit_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_rabbit_4
execute at @e[type=rabbit,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_rabbit_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_rabbit_4
execute at @e[type=rabbit,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_rabbit_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_rabbit_4
execute at @e[type=rabbit,r=20,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_rabbit_4
execute at @e[type=slime,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_slime_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_slime_4
execute at @e[type=slime,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_slime_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_slime_4
execute at @e[type=slime,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_slime_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_slime_4
execute at @e[type=slime,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_slime_4
execute at @e[type=squid,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_squid_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_squid_4
execute at @e[type=squid,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_squid_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_squid_4
execute at @e[type=squid,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_squid_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_squid_4
execute at @e[type=squid,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_squid_4
execute at @e[type=cod,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_fish_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_fish_4
execute at @e[type=cod,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_fish_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_fish_4
execute at @e[type=cod,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_fish_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_fish_4
execute at @e[type=cod,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_fish_4
execute at @e[type=turtle,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_turtle_3,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_turtle_4
execute at @e[type=turtle,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_turtle_2,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_turtle_4
execute at @e[type=turtle,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar_turtle_1,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_turtle_4
execute at @e[type=turtle,r=5,c=1] run replaceitem entity @p[hasitem={item=strat:soul_jar,location=slot.weapon.offhand}] slot.weapon.offhand 0 strat:soul_jar_turtle_4